version: "3"
services:
  db:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: oceankeeper-admin
#      MYSQL_PASSWORD: oceankeeper
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      #- ./db/conf.d:/etc/mysql/conf.d
      - ./db/init.d:/docker-entrypoint-initdb.d
    networks:
      - backend
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name: api_server
    env_file: .devel.env
    environment:
        TJ: "Asia/Seoul"
    depends_on:
      - db
      - redis
    networks:
      - backend
    volumes:
      - ./logs:/home/ubuntu/Ocean-keeper-Server/logs
  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_server
      hostname: redis_server
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - "6379:6379"
      networks:
        - backend
networks:
  backend: