server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  config:
    activate:
      on-profile: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /templates/
      suffix: .mustache
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size : 3MB
      max-request-size: 1MB
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    '[com.server.oceankeeper]': DEBUG
    '[org.hibernate.type]': TRACE
    root: INFO

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  password: ${JWT_PASSWORD}
  secret: ${JWT_SECRET}
