server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${rds_hostname}:${rds_port}/${rds_db_name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds_username}
    password: ${rds_password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update #create update none
    properties:
      '[hibernate.default_batch_fetch_size]': 100
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379

logging:
  level:
    '[com.server.oceankeeper]': INFO

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  password: ${JWT_PASSWORD}
  secret: ${JWT_SECRET}